### ISSUE TITLE
Change license from LGPL

### ISSUE THREAD

**Issue by dudk** [viert/lame#5]
Thank you for resolving my [previous issue](#4) about license. However, I did a little bit more [research](https://www.reddit.com/r/golang/comments/8x4woa/dependency_license_compatibility_code_efficiency/) and found out that [LGPL license is not a good choice](https://groups.google.com/forum/#!topic/golang-nuts/JqOAWBpL-70) for Go library. It's because LGPL doesn't favor static-linking and for Go it's the exact situation, every package is linked statically. By using LGPL for go package you implicitly restrict anybody from re-using your source code. 

You can use any kind of license for this wrapper library because you link lame dynamically.

**Comment by viert** [comment]
God, you do take it quite seriously =)
Would MIT do the job? I heard of it being the most, let's say, "liberal" license among others. I definitely never wanted to sweat it but actually did want people to use my projects any way they like to.

**Comment by dudk** [comment]
Well, I'm building quite ambitious DSP framework, so I want to handle
licenses with care :) I publish my own code with exactly same intentions
and MIT offers the most liberal conditions.

**Comment by dudk** [comment]
Thank you for MIT
